# Description: Deepspeech native client library.

cc_library(
    name = "deepspeech",
    srcs = ["deepspeech.cc"],
    hdrs = ["deepspeech.h"],
    deps = [
        "//tensorflow/core:tensorflow",
    ]
)
